# Form implementation generated from reading ui file './QDesign/tranfer_iface.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(390, 240)
        self.rb_MT = QtWidgets.QRadioButton(parent=Dialog)
        self.rb_MT.setGeometry(QtCore.QRect(10, 20, 110, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.rb_MT.setFont(font)
        self.rb_MT.setChecked(True)
        self.rb_MT.setObjectName("rb_MT")
        self.rb_TM = QtWidgets.QRadioButton(parent=Dialog)
        self.rb_TM.setGeometry(QtCore.QRect(10, 60, 110, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.rb_TM.setFont(font)
        self.rb_TM.setObjectName("rb_TM")
        self.editline_currency = QtWidgets.QLineEdit(parent=Dialog)
        self.editline_currency.setGeometry(QtCore.QRect(90, 100, 113, 26))
        self.editline_currency.setMaxLength(4)
        self.editline_currency.setObjectName("editline_currency")
        self.label_currency = QtWidgets.QLabel(parent=Dialog)
        self.label_currency.setGeometry(QtCore.QRect(20, 105, 61, 18))
        self.label_currency.setObjectName("label_currency")
        self.label_amount = QtWidgets.QLabel(parent=Dialog)
        self.label_amount.setGeometry(QtCore.QRect(20, 145, 58, 18))
        self.label_amount.setObjectName("label_amount")
        self.editline_amount = QtWidgets.QLineEdit(parent=Dialog)
        self.editline_amount.setGeometry(QtCore.QRect(90, 140, 141, 26))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.editline_amount.setFont(font)
        self.editline_amount.setMaxLength(10)
        self.editline_amount.setClearButtonEnabled(False)
        self.editline_amount.setObjectName("editline_amount")
        self.btn_OK = QtWidgets.QPushButton(parent=Dialog)
        self.btn_OK.setGeometry(QtCore.QRect(210, 200, 80, 26))
        self.btn_OK.setObjectName("btn_OK")
        self.btn_cancel = QtWidgets.QPushButton(parent=Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(300, 200, 80, 26))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Transfer"))
        self.rb_MT.setText(_translate("Dialog", "Main -> Trade"))
        self.rb_TM.setText(_translate("Dialog", "Trade -> Main"))
        self.label_currency.setText(_translate("Dialog", "Currency:"))
        self.label_amount.setText(_translate("Dialog", "Amount:"))
        self.btn_OK.setText(_translate("Dialog", "OK"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
